`timescale 1ns / 1ps
//--------------------------------------------------------------------------------------------
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
//  31 2018 21:12:01
//      Component name  : pbest
//--------------------------------------------------------------------------------------------
module pbest(clk_P, reset, ena, x_fit, addr, p_fit, address);
   input            clk_P;
   input            reset;
	input            ena;
   input  [15:0]    x_fit;
	input  [1:0]     addr;
	
   output [2:0]     address;
	reg 	 [2:0]     address;
	
	reg  	 [15:0]    x_fit1;
//	reg  	 [15:0]    p_fit2;
//	reg  	 [15:0]    p_fit3;
	reg 	 [1:0]     addri;
	
   output [15:0]    p_fit;
   reg    [15:0]    p_fit;
   reg    [15:0]    p_fit1;
	
   parameter   	  states_idle = 4'b0001,
                    states_st1 = 4'b0010,
                    states_st2 = 4'b0100,
						  states_st3 = 4'b1000;
						  
   
	always @(posedge clk_P)
		begin
			addri <= addr;
			x_fit1 <= x_fit;
		end
		
   always @(posedge clk_P)
   begin
      if (reset == 1'b1)
      begin
         p_fit <= 0;
       //  best <= 0;
			address <= 0;
      end
      else if(ena == 1'b1)
         case (addri)
            states_idle :
               begin
						p_fit <= 0;
						address <= 0;
               end
            states_st1 :
               begin
                  p_fit1 <= x_fit1;
               end
				states_st2 :
               begin
			//			p_fit2 <= p_fit;
                  if (p_fit1 < x_fit1)
                     p_fit1 <= x_fit1;
               end
				states_st3 :
               begin
						if (x_fit1 < p_fit1)
                     p_fit <= p_fit1;
						else
							p_fit <= x_fit1;
						address <= address + 1;
               end
            default :
               begin
                  p_fit <= 0;
						address <= 0;
               end
         endcase
   end
endmodule
